api_backend/backend/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vrct_app.urls')),

    # rest
    path('api-auth/', include('rest_framework.urls'))
]

api_backend/vrct_app/urls.py
from django.urls import path

from vrct_app.views import *

urlpatterns = [
    # login, logout, index
    path("", IndexView.as_view(), name="home"),
    path("login", CustomLoginView.as_view(), name="login"),
    path("logout", CustomLogoutView.as_view(), name="logout"),

    # ajax
    path("ajax/get-groups-by-training", ajax_get_groups_by_training, name='ajax_get_groups_by_training'),
    path("ajax/get-trainees-by-training", ajax_get_trainees_by_training, name='ajax_get_trainees_by_training'),
    path("ajax/ajax_get_variants_by_bot", ajax_get_variants_by_bot, name='ajax_get_variants_by_bot'),

    # user
    path("user-list", UserList.as_view(), name="user_list"),
    path("create-user", CreateUserView.as_view(), name="create_user"),

    # Trainee
    path("trainee-list", TraineeList.as_view(), name="trainee_list"),
    path("create-trainee", CreateTraineeView.as_view(), name="create_trainee"),

    # create training
    path("training-list", TrainingList.as_view(), name="training_list"),
    path("create-training/training", CreateTrainingTrainingView.as_view(), name="create_training_training"),
    path("create-training/training/success/<training_id>/", CreateTrainingTrainingSuccessView.as_view(), name="create_training_training_success"),
    path("create-training/bot", CreateTrainingBotView.as_view(), name="create_training_bot"),
    path("create-training/bot/success/<bot_id>/", CreateTrainingBotSuccessView.as_view(), name="create_training_bot_success"),
    path("create-training/bot/variant", CreateBotVariantView.as_view(), name="create_bot_variant"),
    path("create-training/bot/variant/success/<bot_variant_id>/", CreateBotVariantSuccessView.as_view(), name="create_bot_variant_success"),
    path("create-training/condition", CreateTrainingConditionView.as_view(), name="create_training_condition"),
    path("create-training/condition/success/<condition_id>", CreateTrainingConditionSuccessView.as_view(), name="create_training_condition_success"),
    path("create-training/group", CreateTrainingGroupView.as_view(), name="create_training_group"),
    path("create-training/group/success/<group_id>", CreateTrainingGroupSuccessView.as_view(), name="create_training_group_success"),

    # run training
    path("start-training", StartTraining.as_view(), name="start_training"),
    path("start-training/<training_id>/<trainee_id>", ChooseCondition.as_view(), name="choose_condition"),
    path("start-training/run/<training_id>/<trainee_id>/<condition_id>", RunTraining.as_view(), name="run_training"),
    path("start-training/run/app/choose/<training_id>/<trainee_id>/<condition_id>", RunTrainingWithAppChooseBotVariant.as_view(), name="run_training_with_app_choose"),
    path("start-training/run/app/websocket/<training_id>/<trainee_id>/<condition_id>/<room_name>", RunTrainingWithAppWebsocket.as_view(), name="run_training_with_app_websocket"),

    # feedback
    path("feedback/start/<training_id>/<trainee_id>/<condition_id>", ShowFeedback.as_view(), name="show_feedback"),

    # export data
    path("export-data", StartExport.as_view(), name="export_data"),
    path("export-data/<training_id>", ExportData.as_view(), name="export_training_data"),
    path("export-data/<training_id>/<model_name>/<type>", export_csv, name="export_export"),

    # rest api
    path('api/api-token-auth/', CustomAuthToken.as_view()),
    path('api/current-trainings-list/', current_running_trainings_list),
    path('api/current-trainings-list-unity/', current_running_trainings_list_unity),
    path('api/update-training-running/', update_training_running),
    path('api/update-training-finished/', update_training_finished),
    path('api/save-trial-data/', save_trial_data),
    path('api/delete-training-data/', delete_training_data),
]

api_backend/vrct_app/models/data.py
from django.db import models
from vrct_app.models.base import VrctBaseModel
from vrct_app.models.trainings import Trainee, Training, Condition, Bot, BotVariant


class DListModel(VrctBaseModel):
    """Model definition for DList. The name of each data table must be unique.
    Here we list all data table models defined beyond to be able to choose them while
    creation of a training."""

    name = models.CharField(verbose_name="name", max_length=255, unique = True)

    class Meta:
        """Meta definition for DListModel."""
        verbose_name = 'DListModel'
        verbose_name_plural = 'DListModels'
        app_label = 'vrct_app'

    def __str__(self):
        return self.name


# -----------------
# Make your own data tables for your trainings
# -----------------

class TutorialTrainingData(VrctBaseModel):
    """ Example of an training data model with bot conversation."""

    BEHAVIOR_CHOICES = [('communicative', 'communicative'), ('reserved', 'reserved')]

    TEST1_CHOICES = [(1, 'one'), (2, 'two'), (3, 'three')]

    # PLEASE INTEGRATE THIS IN EVERY TABLE FOR A NEW TRAINING!
    # basic info about trainee, training etc.
    trainee = models.ForeignKey(Trainee, on_delete=models.CASCADE, related_name="tutorial_data_trainee")
    training = models.ForeignKey(Training, on_delete=models.CASCADE, related_name="tutorial_data_training")
    condition = models.ForeignKey(Condition, on_delete=models.CASCADE, related_name="tutorial_data_condition")
    bot = models.ForeignKey(Bot, on_delete=models.CASCADE, related_name="tutorial_data_bot")
    bot_variant = models.ForeignKey(BotVariant, on_delete=models.CASCADE, related_name="tutorial_data_bot_variant")

    # PLEASE INTEGRATE THIS IN EVERY TABLE FOR A NEW TRAINING!
    # basic trial info (one trial is defined as a question-answer-pair)
    trial_nr = models.IntegerField()    # starts always with 1
    trial_start_time = models.DateTimeField()   # time at which the trial starts = trainee asks a question
    trial_end_time = models.DateTimeField() # time at which the trial end = chatscript sends answer to Unity
    trial_duration = models.FloatField()  # in ms = trial_end_time - trial_start_time

    # PLEASE INTEGRATE THIS IN EVERY TABLE FOR A NEW TRAINING!
    # basic question and answer content variables
    question_content = models.TextField()
    answer_content = models.TextField()

    # bot output variables
    # IMPORTANT: they always must start with 'cs_'
    cs_topic = models.CharField(max_length=255)
    cs_answerCategory = models.CharField(max_length=255)
    cs_actionType = models.CharField(max_length=255)
    cs_questionCounter = models.IntegerField()
    cs_soundFile = models.CharField(max_length=255)
    cs_probFormat = models.CharField(max_length=255)
    cs_randNum = models.IntegerField()

    # bot input variables
    # IMPORTANT: if the variable should/must be categorized by the operator, 
    # you MUST define the variable starting with 'operator_'
    # you also MUST define the verbose_name and a help_text!
    operator_behavior = models.CharField(max_length=255, choices=BEHAVIOR_CHOICES, verbose_name="Behavior", help_text="Please categorize the verbal behavior of the trainee.")

    class Meta:
        """Meta definition for Tutorial Training Data."""
        verbose_name = 'tutorial training data'
        verbose_name_plural = 'tutorial training data'
        app_label = 'vrct_app'
        unique_together = ['trainee', 'training', 'condition', 'bot', 'bot_variant', 'trial_nr']

api_backend/vrct_app/views/ajax.py
from django.http import JsonResponse

from vrct_app.models import ExperimentalGroup, Trainee,Bot, BotVariant

def ajax_get_groups_by_training(request):

    training_id = request.GET.get('training_id', None)
    data = ExperimentalGroup.objects.filter(trainings=training_id).values()

    return JsonResponse(list(data), safe=False)

def ajax_get_trainees_by_training(request):

    training_id = request.GET.get('training_id', None)
    data = Trainee.objects.filter(trainee_training=training_id).values()

    return JsonResponse(list(data), safe=False)

def ajax_get_variants_by_bot(request):

    bot_id = request.GET.get('bot_id', None)
    bot = Bot.objects.get(pk=bot_id)
    data = BotVariant.objects.filter(bot=bot).values()

    return JsonResponse(list(data), safe=False)

api_backend/vrct_app/views/data_export.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, reverse
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect, HttpResponse
import csv
from django.apps import apps

from datetime import datetime

from vrct_app.forms import StartExportForm

from vrct_app.models import Training, Condition, DListModel, QListModel, FListModel

# Start Data export by choosing training
class StartExport(LoginRequiredMixin, TemplateView):

    template_name = "vrct_app/_data/start_export.html"
    form_class = StartExportForm

    login_url = '/login'
    redirect_field_name = 'redirect_to'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):

        context = {
            'training_id': request.POST['training']
        }

        return HttpResponseRedirect(reverse('export_training_data', kwargs=context))


class ExportData(LoginRequiredMixin, TemplateView):

    template_name = "vrct_app/_data/export_data.html"

    login_url = '/login'
    redirect_field_name = 'redirect_to'

    def get(self, request, *args, **kwargs):

        context = super().get_context_data(**kwargs)
        training_id = context['training_id']
        
        data_model_name = ''

        # check data exists
        try:

            # get correct model_name
            pk_dlistmodel = Training.objects.filter(pk=training_id).values_list('data_table', flat=True).get()
            model_name = DListModel.objects.filter(pk=pk_dlistmodel).values_list('name', flat=True).get()
            data_model_name = model_name
        except:
            print('It was not possible to find the DataModel!')

        # get all Conditions
        training_conditions = Condition.objects.filter(trainings=training_id)

        q_names = []
        f_names = []

        # check for each condition if there is already any data in the database (questionnaires, training data)
        for cond in training_conditions:

            # get QListModels of questionnaire
            q_pre = Condition.objects.filter(name=cond).values('questionnaires_pre')
            q_post = Condition.objects.filter(name=cond).values('questionnaires_post')

            if len(q_pre) > 0:
                for q in q_pre:

                    # get name of Qiestionnaires (str)
                    q_name = QListModel.objects.get(pk=q['questionnaires_pre']).name

                    # check if q already in q_names
                    if q_name not in q_names:

                        # add q to list
                        q_names.append(q_name)
                        
            if len(q_post) > 0:
                for q in q_post:
                    q_name = QListModel.objects.get(pk=q['questionnaires_post']).name
                    if q_name not in q_names:
                        q_names.append(q_name)

            if cond.has_feedback:

                try:

                    # get correct model_name
                    model_name = FListModel.objects.get(name=cond.feedback_table).name # trainingData string = name

                    f_names.append(model_name)


                except:

                    print('It was not possible to find the DataModel!')

        context = {
            'training_id': training_id,
            'training_name': Training.objects.get(id=training_id).name,
            'data_model_name': data_model_name,
            'q_names': q_names,
            'f_names': f_names
        }

        return render(request, self.template_name, {'context': context})


def export_csv(request, training_id, model_name, type):

    # get current datetime
    now = datetime.now()
    dt_string = now.strftime("%d%m%Y_%H%M%S")

    # define filename
    filename = model_name + "_" + dt_string

    content_disposition = f'attachment; filename={filename}.csv'

    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = content_disposition

    # get correct model
    if type == "data":
        # get correct model based on model_name
        DModel = apps.get_model(app_label='vrct_app', model_name=model_name)

        # get all data
        q_set = DModel.objects.all()

    elif type == "questionnaire":
        QModel = apps.get_model(app_label='vrct_app', model_name=model_name)

        # get all data
        q_set = QModel.objects.filter(training=Training.objects.get(pk=training_id)).all()

    else:
        FModel = apps.get_model(app_label='vrct_app', model_name=model_name)

        # get all data
        q_set = FModel.objects.filter(training=Training.objects.get(pk=training_id)).all()


    # write data to csv
    opts = q_set.model._meta
    writer = csv.writer(response)
    field_names = [field.name for field in opts.fields]
    # Write a first row with header information
    writer.writerow(field_names)
    # Write data rows
    for obj in q_set:
        writer.writerow([getattr(obj, field, None) for field in field_names])

    return response

api_backend/vrct_app/views/feedback.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import TemplateView

from vrct_app.models import Trainee, Training, Condition, CurrentRunningTraining, TutorialTrainingFeedback, TutorialTrainingData


# ToDo: definitions to fill in the feedback model
def fill_tutorial_training_feedback(trainee_id, training_id, condition_id, user):
    """Calculate necessary variables for tutorial training feedback model"""

    # get correct data
    training_data = TutorialTrainingData.objects.filter(trainee=trainee_id, training=training_id, condition=condition_id).all()

    print(training_data)
    good = training_data.filter(operator_behavior="communicative").count()
    bad = training_data.filter(operator_behavior="reserved").count()

    # get/calculate data
    n_communicative_behavior = (good/good + bad)*100,
    n_reserved_behavior = (bad/good + bad)*100,

    if n_communicative_behavior[0] > 0:
        good_trial_question_content = training_data.filter(operator_behavior="communicative").first().question_content
        good_trial_answer_content = training_data.filter(operator_behavior="communicative").first().answer_content
    else:
        good_trial_question_content = "",
        good_trial_answer_content = "",

    if n_reserved_behavior[0] > 0:
        bad_trial_question_content = training_data.filter(operator_behavior="reserved").first().question_content
        bad_trial_answer_content = training_data.filter(operator_behavior="reserved").first().answer_content
    else:
        bad_trial_question_content = "",
        bad_trial_answer_content = "",

    feedback_data = TutorialTrainingFeedback(
        trainee = Trainee.objects.get(id=trainee_id),
        training = Training.objects.get(id=training_id),
        condition = Condition.objects.get(id=condition_id),
        bot = training_data[0].bot,
        bot_variant = training_data[0].bot_variant,
        n_communicative_behavior = n_communicative_behavior[0],
        n_reserved_behavior = n_reserved_behavior[0],
        good_trial_question_content = good_trial_question_content,
        good_trial_answer_content = good_trial_answer_content,
        bad_trial_question_content = bad_trial_question_content,
        bad_trial_answer_content = bad_trial_answer_content,
        created_by_id = user.id
    )

    feedback_data.save()


# Feedback View
class ShowFeedback(LoginRequiredMixin, TemplateView):

    template_name = ""

    login_url = '/login'
    redirect_field_name = 'redirect_to'

    def get(self, request, *args, **kwargs):

        context = super().get_context_data(**kwargs)
        training_id = context['training_id']
        trainee_id = context['trainee_id']
        condition_id = context['condition_id']

        # get correct Running Training
        current_training = CurrentRunningTraining.objects.get(trainee=trainee_id, training=training_id, condition=condition_id)

        # fill in feedback model and get correct template
        if current_training.training.name == "TutorialTraining":

            # you have to create new template(s) if you define a new training in order to be able to adjust the feedback individually for your training
            self.template_name = "vrct_app/_feedback/tutorialtraining_feedback.html"

            # check if feedback-model already exists
            try: 
                
                TutorialTrainingFeedback.objects.get(trainee=trainee_id, training=training_id, condition=condition_id)

            except:

                fill_tutorial_training_feedback(trainee_id, training_id, condition_id, user=request.user)

            # else: get feedback model
            feedback_model = TutorialTrainingFeedback.objects.get(trainee=trainee_id, training=training_id, condition=condition_id)

        ## if you create a new training, you must hardcode here your feedback definition(s) for your training

        else:

            print("There exists no definition for this Training. Please hard code it...")


        context = {
            'current_training': current_training,
            'feedback_model': feedback_model
        }


        return render(request, self.template_name, {'context': context})

api_backend/vrct_app/templates/vrct_app/_run_training/choose_condition.html
{% extends 'vrct_app/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Start Training Session{% endblock %}

{% block content %}
<div class="row d-flex justify-content-center">
    <div class="text-center col-md-6">
        <h3 class="text-center mt-5"><b>Training:</b> {{context.training_name}}</h3>
    </div>
    <div class="text-center col-md-6">
        <h3 class="text-center mt-5"><b>Trainee:</b> {{context.trainee_name}}</h3>
    </div>
</div>

<div class="row d-flex justify-content-center mt-5">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Condition</th>
            <th scope="col">Status</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
            {% for key, value in context.data.items %} 
            <tr>
                <th scope="row" class="align-middle h5">{{ key }}</th>
                <td>
                    {% for a, b in value.items %}
                        {% if a == 'Questionnaires (Pre)' %}
                        <p><b>{{a}}</b> {% if value.q_pre_finished_all %}<i class="fas fa-check-circle text-success"></i>{% else %}<i class="fas fa-ban text-danger"></i>{% endif %}</p>
                        <p>
                            {% if value.n_q_pre > 0 %}
                            <ul>
                                {% for questionnaire, value in b.items %}
                                    <li>{{questionnaire}}: {{value}}</li>
                                {% endfor %} 
                            </ul>
                            {% else %}
                            <ul>
                                no questionnaires defined
                            </ul>
                            {% endif %}
                        </p>
                        {% elif a == 'Questionnaires (Post)' %}
                        <p><b>{{a}}</b> {% if value.q_post_finished_all %}<i class="fas fa-check-circle text-success"></i>{% else %}<i class="fas fa-ban text-danger"></i>{% endif %}</p>
                        <p>
                            {% if value.n_q_post > 0 %}
                            <ul>
                                {% for questionnaire, value in b.items %}
                                    <li>{{questionnaire}}: {{value}}</li>
                                {% endfor %} 
                            </ul>
                            {% else %}
                            <ul>
                                no questionnaires defined
                            </ul>
                            {% endif %} 
                        </p>
                        {% elif a == 'Training Data' %}
                        <p><b>{{a}}</b> {% if value.training_condition_finished %}<i class="fas fa-check-circle text-success"></i>{% else %}<i class="fas fa-ban text-danger"></i>{% endif %}</p>
                        <p>
                            <ul>
                                <li>{{b.number_trials}} Trial(s) in Database</li>
                            </ul>
                        </p>
                        {% endif %}
                    {% endfor %}
                    
                    {% if value.has_feedback %}
                        <p><b>Feedback</b> {% if value.feedback_finished %}<i class="fas fa-check-circle text-success"></i>{% else %}<i class="fas fa-ban text-danger"></i>{% endif %}</p>
                        {% if value.feedback_finished %}
                            <ul>
                                <li>feedback already saved</li>
                            </ul>
                        {% else %}
                            <ul>
                                <li>feedback not saved yet</li>
                            </ul>
                        {% endif %}
                    {% else %}
                        <p><b>Feedback</b> <i class="fas fa-check-circle text-success"></i></p>
                        <ul>no feedback defined</ul>
                    {% endif %}
                </td>
                <td class="align-middle">
                    {% if not value.training_condition_finished or not value.q_post_finished_all or not value.q_pre_finished_all %}
                    <form action="" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="context" value='{{context}}'></input>
                        <button type="submit" class="btn btn-success" name="start" value='{{key}}'>Start Training Condition</button>
                    </form>
                    {% else %}
                        <p>Condition already finished.</p>
                        {% if value.has_feedback %}
                            <a href="{% url 'show_feedback' training_id=context.training_id trainee_id=context.trainee_id condition_id=value.pk %}"><button class="btn btn-success">Go to FEEDBACK</button></a>
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

api_backend/vrct_app/templates/vrct_app/_run_training/run_training.html
{% extends 'vrct_app/base.html' %}

{% load crispy_forms_tags %}

{% block title %}{% endblock %}

{% block content %}
<div class="row d-flex justify-content-center">

    <div class="text-center col-md-4">
        <div class="h5 my-3"><b>Trainee:</b> {{context.current_training.trainee}}</div>
    </div>
    <div class="text-center col-md-4">
        <div class="h5 my-3"><b>Training:</b> {{context.current_training.training}}</div>
    </div>
    <div class="text-center col-md-4">
        <div class="h5 my-3"><b>Condition:</b> {{context.current_training.condition}}</div>
    </div>
</div>

{% if context.check_ok %}
    <div class="row d-flex justify-content-center">

        {% if context.q_pre %}
            <h1 class="text-center col-md-12 mt-5">{{context.q_name}} (Pre)</h3>
            <h4 class="text-center col-md-12 mt-3">Please answer all questions and click next.</h4>
            <form method="post" class="mx-auto center-text mt-4">
                {% csrf_token %}
                {{ context.form|crispy }}
                <input type="hidden" name="trainee_id" value='{{context.trainee_id}}'></input>
                <input type="hidden" name="training_id" value='{{context.training_id}}'></input>
                <input type="hidden" name="condition_id" value='{{context.condition_id}}'></input>
                <input type="hidden" name="current_training" value='{{context.current_training.pk}}'></input>
                <input type="hidden" name="q_name" value='{{context.q_name}}'></input>
                <input type="hidden" name="q_pre" value='{{context.q_pre}}'></input>
                <input type="hidden" name="q_post" value='{{context.q_post}}'></input>
                <input type="hidden" name="training" value='{{context.q_training}}'></input>
                <input type="hidden" name="check_ok" value='{{context.check_ok}}'></input>
                <input type="hidden" name="qs_dict" value='{{context.qs_dict}}'></input>
                <button type="submit" class="btn btn-lg btn-primary">Next</button>
            </form>
        {% elif context.training %}

            <div class="alert alert-warning mt-5 text-center" role="alert">
                <h3 class="alert-heading">You have answered all Questionnaires!</h3>
                <p>Please talk to your operator, that you have finished the questionnaires. OPERATOR: To start the training, click the button below!</p>
                <hr>

                {% if not context.bot_choosen %}
                <a href="{% url 'run_training_with_app_choose' training_id=context.training_id trainee_id=context.trainee_id condition_id=context.condition_id %}"><button class="btn btn-primary">Start Training</button></a>
                {% else %}
                <a href="{% url 'run_training_with_app_websocket' training_id=context.training_id trainee_id=context.trainee_id condition_id=context.condition_id room_name=context.current_training.ws_room_name %}"><button class="btn btn-primary">Start Training</button></a>
                {% endif %}
            </div>
        {% elif context.q_post %}
            <h1 class="text-center col-md-12 mt-5">{{context.q_name}} (Post)</h3>
            <h4 class="text-center col-md-12 mt-3">Please answer all questions and click next.</h4>
            <form method="post" class="mx-auto center-text mt-4">
                {% csrf_token %}
                {{ context.form|crispy }}
                <input type="hidden" name="trainee_id" value='{{context.trainee_id}}'></input>
                <input type="hidden" name="training_id" value='{{context.training_id}}'></input>
                <input type="hidden" name="condition_id" value='{{context.condition_id}}'></input>
                <input type="hidden" name="current_training" value='{{context.current_training.pk}}'></input>
                <input type="hidden" name="q_name" value='{{context.q_name}}'></input>
                <input type="hidden" name="q_pre" value='{{context.q_pre}}'></input>
                <input type="hidden" name="q_post" value='{{context.q_post}}'></input>
                <input type="hidden" name="training" value='{{context.q_training}}'></input>
                <input type="hidden" name="check_ok" value='{{context.check_ok}}'></input>
                <input type="hidden" name="qs_dict" value='{{context.qs_dict}}'></input>
                <button type="submit" class="btn btn-lg btn-primary">Next</button>
            </form>
        {% else %}
            <div class="alert alert-warning mt-5 text-center" role="alert">
                <h3 class="alert-heading">All data is saved in the database for this condition!</h3>
                <p>To start the feedback session (if one is defined for this condition), click the Button below.</p>
                <hr>
                <a href="{% url 'show_feedback' training_id=context.training_id trainee_id=context.trainee_id condition_id=context.condition_id %}"><button class="btn btn-primary">Go to FEEDBACK</button></a>
            </div>
        {% endif %}

    </div>
{% else %}
    <div class="row d-flex justify-content-center">
        <div class="alert alert-danger" role="alert">
            Something went wrong! Please check your data, since there are data in the database which should not exist at this status of the condition!
        </div>
    </div>
{% endif %}

{% endblock %}

{% block bootstrap4_extra_script %}

{% endblock %}

api_backend/vrct_app/templates/vrct_app/_run_training/start_training.html
{% extends 'vrct_app/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Start Training Session{% endblock %}

{% block content %}
<div class="row d-flex justify-content-center">
    <form method="post" class="mx-auto center-text mt-4">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-lg btn-primary">Next</button>
    </form>
</div>
{% endblock %}

{% block bootstrap4_extra_script %}
<script>
$(document).ready(
    function(){
        $("#id_training").on('change', function(){
            
            var value = $(this).val();

            // Remove options
            $('#id_trainee').empty()

            if (value != '') {

                $.ajax({
                    url: "{% url 'ajax_get_trainees_by_training' %}",
                    data: {
                        'training_id': value 
                    },
                    dataType: 'json',

                    success: function (data) {

                        console.log('data is ' + data)

                        if (data.length > 0) {

                            console.log('data.length > 0')

                            // Remove form errors
                            $("#error_1_id_trainee").remove();

                            $.each(data, function (i, item) {
                                $('#id_trainee').append($('<option>', { 
                                    value: item.id,
                                    text : item.trainee_id
                                }));
                            });

                        } else {

                            $("#error_1_id_trainee").remove();

                            $("#error_1_id_trainee").after("<p class='errorField' id='subject_error_field' style='color: red;'><em></em>" + 'Sorry, there was an error.' + "</p>");
                        }
                            
                    },
                });


            }
    })
})
</script>
{% endblock %}