api_backend/backend/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vrct_app.urls')),

    # rest
    path('api-auth/', include('rest_framework.urls'))
]

api_backend/vrct_app/urls.py
from django.urls import path

from vrct_app.views import *

urlpatterns = [
    # login, logout, index
    path("", IndexView.as_view(), name="home"),
    path("login", CustomLoginView.as_view(), name="login"),
    path("logout", CustomLogoutView.as_view(), name="logout"),

    # ajax
    path("ajax/get-groups-by-training", ajax_get_groups_by_training, name='ajax_get_groups_by_training'),
    path("ajax/get-trainees-by-training", ajax_get_trainees_by_training, name='ajax_get_trainees_by_training'),
    path("ajax/ajax_get_variants_by_bot", ajax_get_variants_by_bot, name='ajax_get_variants_by_bot'),

    # user
    path("user-list", UserList.as_view(), name="user_list"),
    path("create-user", CreateUserView.as_view(), name="create_user"),

    # Trainee
    path("trainee-list", TraineeList.as_view(), name="trainee_list"),
    path("create-trainee", CreateTraineeView.as_view(), name="create_trainee"),

    # create training
    path("training-list", TrainingList.as_view(), name="training_list"),
    path("create-training/training", CreateTrainingTrainingView.as_view(), name="create_training_training"),
    path("create-training/training/success/<training_id>/", CreateTrainingTrainingSuccessView.as_view(), name="create_training_training_success"),
    path("create-training/bot", CreateTrainingBotView.as_view(), name="create_training_bot"),
    path("create-training/bot/success/<bot_id>/", CreateTrainingBotSuccessView.as_view(), name="create_training_bot_success"),
    path("create-training/bot/variant", CreateBotVariantView.as_view(), name="create_bot_variant"),
    path("create-training/bot/variant/success/<bot_variant_id>/", CreateBotVariantSuccessView.as_view(), name="create_bot_variant_success"),
    path("create-training/condition", CreateTrainingConditionView.as_view(), name="create_training_condition"),
    path("create-training/condition/success/<condition_id>", CreateTrainingConditionSuccessView.as_view(), name="create_training_condition_success"),
    path("create-training/group", CreateTrainingGroupView.as_view(), name="create_training_group"),
    path("create-training/group/success/<group_id>", CreateTrainingGroupSuccessView.as_view(), name="create_training_group_success"),

    # run training
    path("start-training", StartTraining.as_view(), name="start_training"),
    path("start-training/<training_id>/<trainee_id>", ChooseCondition.as_view(), name="choose_condition"),
    path("start-training/run/<training_id>/<trainee_id>/<condition_id>", RunTraining.as_view(), name="run_training"),
    path("start-training/run/app/choose/<training_id>/<trainee_id>/<condition_id>", RunTrainingWithAppChooseBotVariant.as_view(), name="run_training_with_app_choose"),
    path("start-training/run/app/websocket/<training_id>/<trainee_id>/<condition_id>/<room_name>", RunTrainingWithAppWebsocket.as_view(), name="run_training_with_app_websocket"),

    # feedback
    path("feedback/start/<training_id>/<trainee_id>/<condition_id>", ShowFeedback.as_view(), name="show_feedback"),

    # export data
    path("export-data", StartExport.as_view(), name="export_data"),
    path("export-data/<training_id>", ExportData.as_view(), name="export_training_data"),
    path("export-data/<training_id>/<model_name>/<type>", export_csv, name="export_export"),

    # rest api
    path('api/api-token-auth/', CustomAuthToken.as_view()),
    path('api/current-trainings-list/', current_running_trainings_list),
    path('api/current-trainings-list-unity/', current_running_trainings_list_unity),
    path('api/update-training-running/', update_training_running),
    path('api/update-training-finished/', update_training_finished),
    path('api/save-trial-data/', save_trial_data),
    path('api/delete-training-data/', delete_training_data),
]

api_backend/vrct_app/models/base.py
# Common infos for all models
from django.db import models
from django.utils.timezone import now
from django.conf import settings


class VrctBaseModel(models.Model):
    """ A abstract model used in each model within vrct."""
    created_at = models.DateTimeField(editable=False)
    updated_at = models.DateTimeField(editable=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        abstract = True

    def save(self, **kwargs):
        if not self.created_at:
            self.created_at = now()
        self.updated_at = now()
        super(VrctBaseModel, self).save()

api_backend/vrct_app/models/trainings.py
from django.db import models
from vrct_app.models.base import VrctBaseModel


class QListModel(VrctBaseModel):
    """Model definition for QList. The name of each questionnaire must be unique.
    Here we list all questionnaire models defined beyond to be able to choose them while
    creation of training condition."""

    name = models.CharField(verbose_name="name", max_length=255, unique = True)

    class Meta:
        """Meta definition for QListModel."""
        verbose_name = 'QListModel'
        verbose_name_plural = 'QListModels'
        app_label = 'vrct_app'

    def __str__(self):
        return self.name

class Training(VrctBaseModel):
    """Model definition for Training. The name of each training must be unique. 
    A training has one fixed data table in which dependent variables for each trials are defined. Thus, all associated
    conditions and bots (and bot variants) have to follow this data table."""

    name = models.CharField(verbose_name="name", max_length=255, unique = True)
    short_description = models.TextField(verbose_name="short description", null=True, blank=True)

    data_table = models.ForeignKey('vrct_app.DListModel', on_delete=models.CASCADE, related_name="data_table_name")

    class Meta:
        """Meta definition for Training."""
        verbose_name = 'training'
        verbose_name_plural = 'trainings'
        app_label = 'vrct_app'

    def __str__(self):
        return self.name


class ExperimentalGroup(VrctBaseModel):
    """Model definition for a ExperimentalGroup. The name of ExperimentalGroup must be unique."""

    name = models.CharField(verbose_name="name", max_length=255, unique = True)

    # many-to-many field: an Condition can be used in multiple Trainings, and a 
    # Training can have multiple Conditions
    trainings = models.ManyToManyField(Training)


    class Meta:
        """Meta definition for Experimental Groups."""
        verbose_name = 'experimental group'
        verbose_name_plural = 'experimental groups'
        app_label = 'vrct_app'

    def __str__(self):
        return self.name

    def get_trainings(self):
        return ", ".join([str(p) for p in self.trainings.all()])


class Bot(VrctBaseModel):
    """Model definition for a ChatScript bot. The name of each bot must be unique. 
    Each bot associated with one experiment MUST follow the same data table."""

    name = models.CharField(verbose_name="name", max_length=255, unique = True)
    vignette = models.TextField(verbose_name="vignette")

    class Meta:
        """Meta definition for Bot."""
        verbose_name = 'bot'
        verbose_name_plural = 'bots'
        app_label = 'vrct_app'

    def __str__(self):
        return self.name

    def get_variants(self):
        return ", ".join([str(p) for p in self.variants.all()])


class BotVariant(VrctBaseModel):
    """Model definition for a bot variant. A bot can have multiple variants. 
    Please see documentation for conversation engine to 
    learn more about bot variants."""

    name = models.CharField(verbose_name="name", max_length=255)
    short_description = models.TextField(verbose_name="short description", null=True, blank=True)
    bot = models.ForeignKey(Bot, on_delete=models.CASCADE, related_name="bot_variant")

    class Meta:
        """Meta definition for Bot Variant."""
        verbose_name = 'botvariant'
        verbose_name_plural = 'botvariants'
        app_label = 'vrct_app'
        unique_together = ['name', 'bot']

    def __str__(self):
        return self.name



class Condition(VrctBaseModel):
    """Model definition for a Training condition (or measurement point). The name of each training condition must be unique.
    Each condition must follow the data table defined in its training."""

    name = models.CharField(verbose_name="name", max_length=255, unique = True)

    # each condition must be associated with at least one Training, but it can be associated with more...
    trainings = models.ManyToManyField(Training)

    # each condition must have at least one bot, but it can have more than one bot...
    # in the operator_application the operator can choose, which bot (and which bot variant) will be used.
    # if there is only one bot (with one variant) in a condition, only this bot can be used in the condition
    bot = models.ForeignKey(Bot, on_delete=models.CASCADE, related_name = 'condition_bot')
    bot_variants = models.ManyToManyField(BotVariant)

    # questionnaires associated with this condition. You can define questionnaires showed before (pre)
    # and after (post) the condtion. Questionnaires are not required...
    questionnaires_pre = models.ManyToManyField(QListModel, related_name="qlist_pre", blank=True)
    questionnaires_post = models.ManyToManyField(QListModel, related_name="qlist_post", blank=True)

    # the scene unity should use in this condition
    unity_scene = models.CharField(verbose_name="unity_scene", max_length=255)

    has_feedback = models.BooleanField(default=False)
    feedback_table = models.ForeignKey('vrct_app.FListModel', on_delete=models.CASCADE, related_name="feedback_table_name", blank=True, null=True)
    
    class Meta:
        """Meta definition for Training Condition."""
        verbose_name = 'training condition'
        verbose_name_plural = 'training conditions'
        app_label = 'vrct_app'

    def __str__(self):
        return self.name

    def get_trainings(self):
        return ", ".join([str(p) for p in self.trainings.all()])

    def get_bot_variants(self):
        return ", ".join([str(p) for p in self.bot_variants.all()])

    def get_questionnaires_pre(self):
        return ",".join([str(p) for p in self.questionnaires_pre.all()])

    def get_questionnaires_post(self):
        return ",".join([str(p) for p in self.questionnaires_post.all()])


class Trainee(VrctBaseModel):
    """Model definition for Trainee. The id of each Trainee must be unique."""

    trainee_id = models.CharField(verbose_name="Trainee id", max_length=255, unique = True)
    trainee_training = models.ForeignKey(Training, on_delete=models.CASCADE, related_name = 'trainee_training')
    trainee_group = models.ForeignKey(ExperimentalGroup, on_delete=models.CASCADE, related_name = 'trainee_exp_group')
    trainee_is_pilot = models.BooleanField(verbose_name="Trainee is pilot", default = False)
    
    class Meta:
        """Meta definition for Trainee."""
        verbose_name = 'Trainee'
        verbose_name_plural = 'Trainees'
        app_label = 'vrct_app'

    def __str__(self):
        return self.trainee_id


class CurrentRunningTraining(VrctBaseModel):
    '''Model definition for Current Running Training'''

    trainee = models.ForeignKey(Trainee, on_delete=models.CASCADE, related_name='running_training_trainee')
    training = models.ForeignKey(Training, on_delete=models.CASCADE, related_name = 'running_training_training')
    condition = models.ForeignKey(Condition, on_delete=models.CASCADE, related_name = 'running_training_condition')
    bot = models.CharField(verbose_name="bot", max_length=255, default='TutorialBot')
    bot_variant = models.CharField(verbose_name="bot variant", max_length=255, default='')

    q_pre_finished = models.BooleanField(default=False)
    qs_pre = models.TextField(default='')
    websocket_running = models.BooleanField(default=False)
    ws_room_name = models.CharField(verbose_name="ws_room_name", max_length=255, default='')
    training_running = models.BooleanField(default=False)
    training_finished = models.BooleanField(default=False)
    qs_post = models.TextField(default='')
    q_post_finished = models.BooleanField(default=False)

    class Meta:
        """Meta definition for Current Running Training."""
        verbose_name = 'Current Running Training'
        verbose_name_plural = 'Current Running Trainings'
        app_label = 'vrct_app'
        unique_together = ['trainee', 'training', 'condition', 'bot', 'bot_variant']

api_backend/vrct_app/views/ajax.py
from django.http import JsonResponse

from vrct_app.models import ExperimentalGroup, Trainee,Bot, BotVariant

def ajax_get_groups_by_training(request):

    training_id = request.GET.get('training_id', None)
    data = ExperimentalGroup.objects.filter(trainings=training_id).values()

    return JsonResponse(list(data), safe=False)

def ajax_get_trainees_by_training(request):

    training_id = request.GET.get('training_id', None)
    data = Trainee.objects.filter(trainee_training=training_id).values()

    return JsonResponse(list(data), safe=False)

def ajax_get_variants_by_bot(request):

    bot_id = request.GET.get('bot_id', None)
    bot = Bot.objects.get(pk=bot_id)
    data = BotVariant.objects.filter(bot=bot).values()

    return JsonResponse(list(data), safe=False)

api_backend/vrct_app/views/feedback.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import TemplateView

from vrct_app.models import Trainee, Training, Condition, CurrentRunningTraining, TutorialTrainingFeedback, TutorialTrainingData


# ToDo: definitions to fill in the feedback model
def fill_tutorial_training_feedback(trainee_id, training_id, condition_id, user):
    """Calculate necessary variables for tutorial training feedback model"""

    # get correct data
    training_data = TutorialTrainingData.objects.filter(trainee=trainee_id, training=training_id, condition=condition_id).all()

    print(training_data)
    good = training_data.filter(operator_behavior="communicative").count()
    bad = training_data.filter(operator_behavior="reserved").count()

    # get/calculate data
    n_communicative_behavior = (good/good + bad)*100,
    n_reserved_behavior = (bad/good + bad)*100,

    if n_communicative_behavior[0] > 0:
        good_trial_question_content = training_data.filter(operator_behavior="communicative").first().question_content
        good_trial_answer_content = training_data.filter(operator_behavior="communicative").first().answer_content
    else:
        good_trial_question_content = "",
        good_trial_answer_content = "",

    if n_reserved_behavior[0] > 0:
        bad_trial_question_content = training_data.filter(operator_behavior="reserved").first().question_content
        bad_trial_answer_content = training_data.filter(operator_behavior="reserved").first().answer_content
    else:
        bad_trial_question_content = "",
        bad_trial_answer_content = "",

    feedback_data = TutorialTrainingFeedback(
        trainee = Trainee.objects.get(id=trainee_id),
        training = Training.objects.get(id=training_id),
        condition = Condition.objects.get(id=condition_id),
        bot = training_data[0].bot,
        bot_variant = training_data[0].bot_variant,
        n_communicative_behavior = n_communicative_behavior[0],
        n_reserved_behavior = n_reserved_behavior[0],
        good_trial_question_content = good_trial_question_content,
        good_trial_answer_content = good_trial_answer_content,
        bad_trial_question_content = bad_trial_question_content,
        bad_trial_answer_content = bad_trial_answer_content,
        created_by_id = user.id
    )

    feedback_data.save()


# Feedback View
class ShowFeedback(LoginRequiredMixin, TemplateView):

    template_name = ""

    login_url = '/login'
    redirect_field_name = 'redirect_to'

    def get(self, request, *args, **kwargs):

        context = super().get_context_data(**kwargs)
        training_id = context['training_id']
        trainee_id = context['trainee_id']
        condition_id = context['condition_id']

        # get correct Running Training
        current_training = CurrentRunningTraining.objects.get(trainee=trainee_id, training=training_id, condition=condition_id)

        # fill in feedback model and get correct template
        if current_training.training.name == "TutorialTraining":

            # you have to create new template(s) if you define a new training in order to be able to adjust the feedback individually for your training
            self.template_name = "vrct_app/_feedback/tutorialtraining_feedback.html"

            # check if feedback-model already exists
            try: 
                
                TutorialTrainingFeedback.objects.get(trainee=trainee_id, training=training_id, condition=condition_id)

            except:

                fill_tutorial_training_feedback(trainee_id, training_id, condition_id, user=request.user)

            # else: get feedback model
            feedback_model = TutorialTrainingFeedback.objects.get(trainee=trainee_id, training=training_id, condition=condition_id)

        ## if you create a new training, you must hardcode here your feedback definition(s) for your training

        else:

            print("There exists no definition for this Training. Please hard code it...")


        context = {
            'current_training': current_training,
            'feedback_model': feedback_model
        }


        return render(request, self.template_name, {'context': context})

api_backend/vrct_app/templates/vrct_app/_trainees/create_trainee.html
{% extends 'vrct_app/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Create new Trainee{% endblock %}

{% block content %}
<div class="row d-flex justify-content-center">
    <form method="post" class="mx-auto center-text mt-4">
        {% csrf_token %}
        <table>
          {{ form|crispy }}
        </table>
        {% if error %}
            <span class="text-danger mt-3 lead mb-3">{{ error }}</span>
        {% endif %}
        <button type="submit" class="btn btn-lg btn-primary">Create</button>
    </form>
</div>
{% endblock %}

<!-- ToDo: ajax and set group based on choosen training: https://stackoverflow.com/questions/59361850/how-to-fill-a-form-field-based-on-another-field-in-django-template-using-ajaxjq -->
{% block bootstrap4_extra_script %}
<script>
$(document).ready(
    function(){
        $("#id_trainee_training").on('change', function(){
            var value = $(this).val();

            // Remove options
            $('#id_trainee_group').empty()

            if (value != '') {

                $.ajax({
                    url: "{% url 'ajax_get_groups_by_training' %}",
                    data: {
                        'training_id': value 
                    },
                    dataType: 'json',

                    success: function (data) {

                        console.log('data is ' + data)

                        if (data.length > 0) {

                            console.log('data.length > 0')

                            // Remove form errors
                            $("#subject_error_field").remove();

                            $.each(data, function (i, item) {
                                $('#id_trainee_group').append($('<option>', { 
                                    value: item.id,
                                    text : item.name 
                                }));
                            });

                        } else {

                            $("#subject_error_field").remove();

                            $("#id_trainee_group").after("<p class='errorField' id='subject_error_field' style='color: red;'><em></em>" + 'Sorry, there was an error.' + "</p>");
                        }
                            
                    },
                });


            }
    })
})
</script>
{% endblock %}

api_backend/vrct_app/templates/vrct_app/_trainees/trainee_list.html
{% extends 'vrct_app/base.html' %}

{% load crispy_forms_tags %}

{% block title %}All Trainees{% endblock %}

{% block content %}
<div class="row d-flex justify-content-center mt-5">
    {% if trainee_list %}
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">ID</th>
                <th scope="col">Group</th>
                <th scope="col">Training</th>
                <th scope="col">Is Pilot?</th>
            </tr>
            </thead>
            <tbody>
                {% for trainee in trainee_list %}
                <tr>
                    <th scope="row">{{ trainee.pk }}</th>
                    <td>{{ trainee.trainee_id }}</td>
                    <td>{{ trainee.trainee_group }}</td>
                    <td>{{ trainee.trainee_training }}</td>
                    <td>{{ trainee.trainee_is_pilot }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-danger mt-5" role="alert">
            There are no Trainees in the database!
        </div>
    {% endif %}
</div>


<!--Pagination-->
{% if is_paginated %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
            <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous</a>
            </li>
        {% else %}
            <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
        {% endif %}

        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active" aria-current="page">
                <span class="page-link">
                    {{ i }}
                    <span class="sr-only">(current)</span>
                </span>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
            <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
            </li>
        {% else %}
            <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
            </li>
        {% endif %}
        </ul>
    </nav>
{% endif %}
<!--end of Pagination-->


{% endblock %}